# .streamlit/secrets.toml file

# Your Anthropic API key (replace with your actual key, keep the quotes)
ANTHROPIC_API_KEY = "YOUR_ANTHROPIC_API_KEY_HERE"

# Note: Make sure there are no spaces before or after the equals sign
# The format should be exactly: KEY = "VALUE"
